theory Group_Further_Theory
  imports Main "Jacobson_Basic_Algebra.Group_Theory"

begin

section \<open>Subgroup Generated by a Subset\<close>

context group 
begin

inductive_set generate :: "'a set \<Rightarrow> 'a set"
  for H where
    unit:  "\<one> \<in> generate H"
  | incl: "a \<in> H \<Longrightarrow> a \<in> generate H"
  | inv:  "a \<in> H \<Longrightarrow> inverse a \<in> generate H"
  | mult:  "a \<in> generate H \<Longrightarrow> b \<in> generate H \<Longrightarrow> a \<cdot> b \<in> generate H"

definition subgroup_generated :: "'a set \<Rightarrow> 'a set"
  where "subgroup_generated S = generate (G \<inter> S)"

lemma subgroup_generated_is_subgroup:
  fixes H
  shows "subgroup G (subgroup_generated H) (\<cdot>) \<one>" sorry

end (* group *)

end